
requires 'Simple::Accessor' => 0;
#requires 'Mojo::UserAgent' => 0;
requires 'JSON::PP'        => 0;
requires 'Exporter', '5.59'; # only need 5.57, but force it in Carton for 5.8.5
requires 'HTTP::Tinyish' => 0;
