
## 
## modules use to FatPack
##	run maint/upgrade-fatlib.pl after updating this file
##

requires 'Simple::Accessor' => '1.13';
requires 'JSON::PP'         => 0;
requires 'Exporter'         => '5.59';
requires 'HTTP::Tinyish'    => 0;
requires 'File::pushd'      => 0;
requires 'File::Which'      => 0;
requires 'File::Basename'   => 0;
requires 'Umask::Local'     => 0;

requires 'Digest::Perl::MD5' => 0; # embed method to check tarball signature