name: cnext-fatpack

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  cnext:
    env:
      # some plugins still needs this to run their tests...
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 0
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0

    runs-on: ubuntu-latest

    steps:
      # no need to checkout
      #- uses: actions/checkout@v2

      - name: perl -V
        run: perl -V

      - name: "%Config"
        run: perl -MConfig -MTest::More -E 'note explain \%Config'

      - name: perl '-V:install.*'
        run: perl '-V:install.*'

      - name: install cnext
        run: |
          curl -L https://git.io/cnext | sudo perl - self-install
          which cnext
          cnext --version

      # sudo ./cnext from-tarball -d https://github.com/${{ github.repository }}/archive/${{ github.sha }}.tar.gz
      - name: cnext from-tarball A1z-Html
        run: |
          sudo cnext from-tarball -d https://github.com/next-cpan/A1z-Html/archive/p5.tar.gz
