name: cnext-makefile

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  makefile:
    env:
      # some plugins still needs this to run their tests...
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 0
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0
      # would be better to find a different module without deps
      CPLAY_MODULE: "Algorithm::Diff"
      CPLAY_DISTRO: "Algorithm-Diff"

    runs-on: ubuntu-latest

    steps:
      # no need to checkout
      #- uses: actions/checkout@v2

      - name: perl -V
        run: perl -V

      - name: install cpm
        run: |
          curl -fsSL --compressed https://git.io/cpm | sudo perl - install -g App::cpm

      # install module using cpm
      - name: "cpm ${{ env.CPLAY_MODULE }} & deps"
        run: |
          sudo cpm install -g --show-build-log-on-failure ${{ env.CPLAY_MODULE }}
          perl -m${{ env.CPLAY_MODULE }} -e1

      - name: remove ${{ env.CPLAY_MODULE }}
        run: |
          sudo rm -f $(perldoc -lm ${{ env.CPLAY_MODULE }})

      - name: install cnext
        run: |
          curl -L https://git.io/cnext | sudo perl - self-install
          which cnext
          cnext --version

      - name: cnext from-tarball ${{ env.CPLAY_DISTRO }}
        run: |
          sudo cnext from-tarball -d https://github.com/next-cpan/${{ env.CPLAY_DISTRO }}/archive/p5.tar.gz

      - name: check module is installed
        run: |
          perl -m${{ env.CPLAY_MODULE }} -e1
