name: cnext-build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    env:
      # some plugins still needs this to run their tests...
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 0
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0
      # would be better to find a different module without deps
      CNEXT_MODULE: "Acme::Alien::DontPanic"
      CNEXT_DISTRO: "Acme-Alien-DontPanic"

    runs-on: ubuntu-latest

    steps:
      # no need to checkout
      #- uses: actions/checkout@v2

      - name: perl -V
        run: perl -V

      - name: "Install deps with cpm"
        uses: perl-actions/install-cpm@v1.3
        with:
          install: |
           ${{ env.CNEXT_MODULE }}
           Test2::Suite

      - name: remove ${{ env.CNEXT_MODULE }}
        run: |
          sudo rm -f $(perldoc -lm ${{ env.CNEXT_MODULE }})

      - name: install cnext
        run: |
          curl -L https://git.io/cnext | sudo perl - self-install
          which cnext
          cnext --version

      - name: cnext from-tarball ${{ env.CNEXT_DISTRO }}
        run: |
          sudo cnext from-tarball -d https://github.com/next-cpan/${{ env.CNEXT_DISTRO }}/archive/p5.tar.gz

      - name: check module is installed
        run: |
          perl -m${{ env.CNEXT_MODULE }} -e1
